/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R403RouteImport } from './routes/403'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as BanDoIndexRouteImport } from './routes/ban-do.index'
import { Route as DoiTacIndexRouteImport } from './routes/doi-tac.index'
import { Route as HopDongIndexRouteImport } from './routes/hop-dong.index'
import { Route as HopDongIdRouteImport } from './routes/hop-dong.$id'
import { Route as HopDongMoiRouteImport } from './routes/hop-dong.moi'
import { Route as NhacLichIndexRouteImport } from './routes/nhac-lich.index'
import { Route as RaoBanIndexRouteImport } from './routes/rao-ban.index'
import { Route as TaiSanIndexRouteImport } from './routes/tai-san.index'
import { Route as TaiSanIdRouteImport } from './routes/tai-san.$id'
import { Route as TaiSanMoiRouteImport } from './routes/tai-san.moi'
import { Route as ThuChiIndexRouteImport } from './routes/thu-chi.index'
import { Route as TinDangIndexRouteImport } from './routes/tin-dang.index'
import { Route as TinDangSlugRouteImport } from './routes/tin-dang.$slug'
import { Route as TaiSanIdSuaRouteImport } from './routes/tai-san.$id_.sua'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/admin/properties',
  path: '/admin/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const BanDoIndexRoute = BanDoIndexRouteImport.update({
  id: '/ban-do/',
  path: '/ban-do/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoiTacIndexRoute = DoiTacIndexRouteImport.update({
  id: '/doi-tac/',
  path: '/doi-tac/',
  getParentRoute: () => rootRouteImport,
} as any)
const HopDongIndexRoute = HopDongIndexRouteImport.update({
  id: '/hop-dong/',
  path: '/hop-dong/',
  getParentRoute: () => rootRouteImport,
} as any)
const HopDongIdRoute = HopDongIdRouteImport.update({
  id: '/hop-dong/$id',
  path: '/hop-dong/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HopDongMoiRoute = HopDongMoiRouteImport.update({
  id: '/hop-dong/moi',
  path: '/hop-dong/moi',
  getParentRoute: () => rootRouteImport,
} as any)
const NhacLichIndexRoute = NhacLichIndexRouteImport.update({
  id: '/nhac-lich/',
  path: '/nhac-lich/',
  getParentRoute: () => rootRouteImport,
} as any)
const RaoBanIndexRoute = RaoBanIndexRouteImport.update({
  id: '/rao-ban/',
  path: '/rao-ban/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiSanIndexRoute = TaiSanIndexRouteImport.update({
  id: '/tai-san/',
  path: '/tai-san/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiSanIdRoute = TaiSanIdRouteImport.update({
  id: '/tai-san/$id',
  path: '/tai-san/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiSanMoiRoute = TaiSanMoiRouteImport.update({
  id: '/tai-san/moi',
  path: '/tai-san/moi',
  getParentRoute: () => rootRouteImport,
} as any)
const ThuChiIndexRoute = ThuChiIndexRouteImport.update({
  id: '/thu-chi/',
  path: '/thu-chi/',
  getParentRoute: () => rootRouteImport,
} as any)
const TinDangIndexRoute = TinDangIndexRouteImport.update({
  id: '/tin-dang/',
  path: '/tin-dang/',
  getParentRoute: () => rootRouteImport,
} as any)
const TinDangSlugRoute = TinDangSlugRouteImport.update({
  id: '/tin-dang/$slug',
  path: '/tin-dang/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiSanIdSuaRoute = TaiSanIdSuaRouteImport.update({
  id: '/tai-san/$id_/sua',
  path: '/tai-san/$id/sua',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-listings': typeof MyListingsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/hop-dong/$id': typeof HopDongIdRoute
  '/hop-dong/moi': typeof HopDongMoiRoute
  '/tai-san/$id': typeof TaiSanIdRoute
  '/tai-san/moi': typeof TaiSanMoiRoute
  '/tin-dang/$slug': typeof TinDangSlugRoute
  '/ban-do/': typeof BanDoIndexRoute
  '/doi-tac/': typeof DoiTacIndexRoute
  '/hop-dong/': typeof HopDongIndexRoute
  '/nhac-lich/': typeof NhacLichIndexRoute
  '/rao-ban/': typeof RaoBanIndexRoute
  '/tai-san/': typeof TaiSanIndexRoute
  '/thu-chi/': typeof ThuChiIndexRoute
  '/tin-dang/': typeof TinDangIndexRoute
  '/tai-san/$id/sua': typeof TaiSanIdSuaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-listings': typeof MyListingsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/hop-dong/$id': typeof HopDongIdRoute
  '/hop-dong/moi': typeof HopDongMoiRoute
  '/tai-san/$id': typeof TaiSanIdRoute
  '/tai-san/moi': typeof TaiSanMoiRoute
  '/tin-dang/$slug': typeof TinDangSlugRoute
  '/ban-do': typeof BanDoIndexRoute
  '/doi-tac': typeof DoiTacIndexRoute
  '/hop-dong': typeof HopDongIndexRoute
  '/nhac-lich': typeof NhacLichIndexRoute
  '/rao-ban': typeof RaoBanIndexRoute
  '/tai-san': typeof TaiSanIndexRoute
  '/thu-chi': typeof ThuChiIndexRoute
  '/tin-dang': typeof TinDangIndexRoute
  '/tai-san/$id/sua': typeof TaiSanIdSuaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-listings': typeof MyListingsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/hop-dong/$id': typeof HopDongIdRoute
  '/hop-dong/moi': typeof HopDongMoiRoute
  '/tai-san/$id': typeof TaiSanIdRoute
  '/tai-san/moi': typeof TaiSanMoiRoute
  '/tin-dang/$slug': typeof TinDangSlugRoute
  '/ban-do/': typeof BanDoIndexRoute
  '/doi-tac/': typeof DoiTacIndexRoute
  '/hop-dong/': typeof HopDongIndexRoute
  '/nhac-lich/': typeof NhacLichIndexRoute
  '/rao-ban/': typeof RaoBanIndexRoute
  '/tai-san/': typeof TaiSanIndexRoute
  '/thu-chi/': typeof ThuChiIndexRoute
  '/tin-dang/': typeof TinDangIndexRoute
  '/tai-san/$id_/sua': typeof TaiSanIdSuaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/my-listings'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/admin/properties'
    | '/hop-dong/$id'
    | '/hop-dong/moi'
    | '/tai-san/$id'
    | '/tai-san/moi'
    | '/tin-dang/$slug'
    | '/ban-do/'
    | '/doi-tac/'
    | '/hop-dong/'
    | '/nhac-lich/'
    | '/rao-ban/'
    | '/tai-san/'
    | '/thu-chi/'
    | '/tin-dang/'
    | '/tai-san/$id/sua'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/my-listings'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/admin/properties'
    | '/hop-dong/$id'
    | '/hop-dong/moi'
    | '/tai-san/$id'
    | '/tai-san/moi'
    | '/tin-dang/$slug'
    | '/ban-do'
    | '/doi-tac'
    | '/hop-dong'
    | '/nhac-lich'
    | '/rao-ban'
    | '/tai-san'
    | '/thu-chi'
    | '/tin-dang'
    | '/tai-san/$id/sua'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/my-listings'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/admin/properties'
    | '/hop-dong/$id'
    | '/hop-dong/moi'
    | '/tai-san/$id'
    | '/tai-san/moi'
    | '/tin-dang/$slug'
    | '/ban-do/'
    | '/doi-tac/'
    | '/hop-dong/'
    | '/nhac-lich/'
    | '/rao-ban/'
    | '/tai-san/'
    | '/thu-chi/'
    | '/tin-dang/'
    | '/tai-san/$id_/sua'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MyListingsRoute: typeof MyListingsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  HopDongIdRoute: typeof HopDongIdRoute
  HopDongMoiRoute: typeof HopDongMoiRoute
  TaiSanIdRoute: typeof TaiSanIdRoute
  TaiSanMoiRoute: typeof TaiSanMoiRoute
  TinDangSlugRoute: typeof TinDangSlugRoute
  BanDoIndexRoute: typeof BanDoIndexRoute
  DoiTacIndexRoute: typeof DoiTacIndexRoute
  HopDongIndexRoute: typeof HopDongIndexRoute
  NhacLichIndexRoute: typeof NhacLichIndexRoute
  RaoBanIndexRoute: typeof RaoBanIndexRoute
  TaiSanIndexRoute: typeof TaiSanIndexRoute
  ThuChiIndexRoute: typeof ThuChiIndexRoute
  TinDangIndexRoute: typeof TinDangIndexRoute
  TaiSanIdSuaRoute: typeof TaiSanIdSuaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/admin/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ban-do/': {
      id: '/ban-do/'
      path: '/ban-do'
      fullPath: '/ban-do/'
      preLoaderRoute: typeof BanDoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doi-tac/': {
      id: '/doi-tac/'
      path: '/doi-tac'
      fullPath: '/doi-tac/'
      preLoaderRoute: typeof DoiTacIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hop-dong/': {
      id: '/hop-dong/'
      path: '/hop-dong'
      fullPath: '/hop-dong/'
      preLoaderRoute: typeof HopDongIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hop-dong/$id': {
      id: '/hop-dong/$id'
      path: '/hop-dong/$id'
      fullPath: '/hop-dong/$id'
      preLoaderRoute: typeof HopDongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hop-dong/moi': {
      id: '/hop-dong/moi'
      path: '/hop-dong/moi'
      fullPath: '/hop-dong/moi'
      preLoaderRoute: typeof HopDongMoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nhac-lich/': {
      id: '/nhac-lich/'
      path: '/nhac-lich'
      fullPath: '/nhac-lich/'
      preLoaderRoute: typeof NhacLichIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rao-ban/': {
      id: '/rao-ban/'
      path: '/rao-ban'
      fullPath: '/rao-ban/'
      preLoaderRoute: typeof RaoBanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-san/': {
      id: '/tai-san/'
      path: '/tai-san'
      fullPath: '/tai-san/'
      preLoaderRoute: typeof TaiSanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-san/$id': {
      id: '/tai-san/$id'
      path: '/tai-san/$id'
      fullPath: '/tai-san/$id'
      preLoaderRoute: typeof TaiSanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-san/moi': {
      id: '/tai-san/moi'
      path: '/tai-san/moi'
      fullPath: '/tai-san/moi'
      preLoaderRoute: typeof TaiSanMoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thu-chi/': {
      id: '/thu-chi/'
      path: '/thu-chi'
      fullPath: '/thu-chi/'
      preLoaderRoute: typeof ThuChiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-dang/': {
      id: '/tin-dang/'
      path: '/tin-dang'
      fullPath: '/tin-dang/'
      preLoaderRoute: typeof TinDangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-dang/$slug': {
      id: '/tin-dang/$slug'
      path: '/tin-dang/$slug'
      fullPath: '/tin-dang/$slug'
      preLoaderRoute: typeof TinDangSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-san/$id_/sua': {
      id: '/tai-san/$id_/sua'
      path: '/tai-san/$id/sua'
      fullPath: '/tai-san/$id/sua'
      preLoaderRoute: typeof TaiSanIdSuaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  ConfirmEmailRoute: ConfirmEmailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MyListingsRoute: MyListingsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  HopDongIdRoute: HopDongIdRoute,
  HopDongMoiRoute: HopDongMoiRoute,
  TaiSanIdRoute: TaiSanIdRoute,
  TaiSanMoiRoute: TaiSanMoiRoute,
  TinDangSlugRoute: TinDangSlugRoute,
  BanDoIndexRoute: BanDoIndexRoute,
  DoiTacIndexRoute: DoiTacIndexRoute,
  HopDongIndexRoute: HopDongIndexRoute,
  NhacLichIndexRoute: NhacLichIndexRoute,
  RaoBanIndexRoute: RaoBanIndexRoute,
  TaiSanIndexRoute: TaiSanIndexRoute,
  ThuChiIndexRoute: ThuChiIndexRoute,
  TinDangIndexRoute: TinDangIndexRoute,
  TaiSanIdSuaRoute: TaiSanIdSuaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
